"""
AI Fitness Coach v1 — Sync Engine

Handles cross-system synchronization between wger and Tandoor:
- Macro targets → meal planning constraints
- Recipe → calorie allocation
- Meal plan → shopping list
- Daily intake → optional wger sync
"""
from typing import Optional
from datetime import date, datetime, timedelta
from app.providers.wger import WgerProvider
from app.providers.tandoor import TandoorProvider
import logging

logger = logging.getLogger(__name__)


class SyncEngine:
    """
    Orchestrates data flow between external systems.

    This is where the "hidden complexity" lives — keeping wger
    and Tandoor in sync with each other and with the user's plan.
    """

    def __init__(self, wger: WgerProvider, tandoor: TandoorProvider):
        self.wger = wger
        self.tandoor = tandoor

    async def gather_planning_data(self, profile: dict) -> dict:
        """
        Gather all data needed for LLM planning from both providers.

        Returns a consolidated data package for the planner.
        """
        data = {
            "recent_workouts": None,
            "current_weight": None,
            "weight_trend": None,
            "available_recipes": None,
            "current_meal_plan": None,
        }

        # ── wger data ──
        try:
            # Recent workout logs (last 2 weeks)
            two_weeks_ago = (date.today() - timedelta(days=14)).isoformat()
            data["recent_workouts"] = await self.wger.list_workout_logs(
                date_from=two_weeks_ago
            )

            # Current body weight + trend
            weight_entries = await self.wger.list_weight_entries(limit=10)
            entries = weight_entries.get("results", [])
            if entries:
                data["current_weight"] = float(entries[0]["weight"])
                if len(entries) >= 3:
                    recent_avg = sum(float(e["weight"]) for e in entries[:3]) / 3
                    older_avg = sum(float(e["weight"]) for e in entries[-3:]) / 3
                    diff = recent_avg - older_avg
                    if diff < -0.5:
                        data["weight_trend"] = "down"
                    elif diff > 0.5:
                        data["weight_trend"] = "up"
                    else:
                        data["weight_trend"] = "stable"

        except Exception as e:
            logger.warning(f"Failed to gather wger data: {e}")

        # ── Tandoor data ──
        try:
            # Available recipes
            recipes = await self.tandoor.list_recipes(limit=100)
            recipe_list = recipes.get("results", recipes) if isinstance(recipes, dict) else recipes
            data["available_recipes"] = [
                {
                    "id": r["id"],
                    "name": r["name"],
                    "working_time": r.get("working_time", 0),
                    "keywords": [kw.get("name", "") for kw in r.get("keywords", [])],
                }
                for r in recipe_list[:50]  # Limit for LLM context
            ]

            # Current meal plan (this week)
            today = date.today()
            week_start = today - timedelta(days=today.weekday())
            week_end = week_start + timedelta(days=6)
            data["current_meal_plan"] = await self.tandoor.list_meal_plans(
                from_date=week_start.isoformat(),
                to_date=week_end.isoformat(),
            )

        except Exception as e:
            logger.warning(f"Failed to gather Tandoor data: {e}")

        return data

    async def sync_workout_plan_to_wger(
        self,
        workout_plan: dict,
        week_start: str,
    ) -> dict:
        """
        Write the generated workout plan to wger as a routine.

        Returns the created routine info.
        """
        try:
            # Create routine
            routine = await self.wger.create_routine(
                name=f"AI Coach Plan - {week_start}",
                description="Generated by AI Fitness Coach",
                start_date=week_start,
            )
            routine_id = routine["id"]

            # Create days and exercises
            for day_data in workout_plan.get("days", []):
                if day_data.get("is_rest_day"):
                    day = await self.wger.create_day(
                        routine_id=routine_id,
                        name=day_data["day"],
                        description=f"{day_data.get('focus', 'Rest Day')}",
                        is_rest=True,
                        order=day_data.get("day_number", 1),
                    )
                    continue

                day = await self.wger.create_day(
                    routine_id=routine_id,
                    name=day_data["day"],
                    description=day_data.get("focus", ""),
                    order=day_data.get("day_number", 1),
                )
                day_id = day["id"]

                for idx, exercise in enumerate(day_data.get("exercises", [])):
                    # Create slot for this exercise
                    slot = await self.wger.create_slot(
                        day_id=day_id,
                        order=idx + 1,
                    )

                    # Add exercise to slot (if we have the wger exercise ID)
                    if exercise.get("exercise_id"):
                        await self.wger.create_slot_entry(
                            slot_id=slot["id"],
                            exercise_id=exercise["exercise_id"],
                        )

            return {"routine_id": routine_id, "status": "synced"}

        except Exception as e:
            logger.error(f"Failed to sync workout to wger: {e}")
            return {"status": "failed", "error": str(e)}

    async def sync_meal_plan_to_tandoor(
        self,
        meal_plan: dict,
        week_start: str,
    ) -> dict:
        """
        Write the generated meal plan to Tandoor.

        Returns sync status.
        """
        try:
            # Get or create meal types
            meal_types = await self.tandoor.get_meal_types()
            if isinstance(meal_types, dict):
                meal_types = meal_types.get("results", [])

            type_map = {mt["name"].lower(): mt["id"] for mt in meal_types}

            # Create default meal types if they don't exist
            for mt_name in ["Breakfast", "Lunch", "Dinner", "Snack"]:
                if mt_name.lower() not in type_map:
                    created = await self.tandoor.create_meal_type(mt_name)
                    type_map[mt_name.lower()] = created["id"]

            synced_count = 0
            start = datetime.fromisoformat(week_start)

            for day_data in meal_plan.get("days", []):
                day_offset = day_data.get("day_number", 1) - 1
                plan_date = (start + timedelta(days=day_offset)).strftime("%Y-%m-%d")

                for meal in day_data.get("meals", []):
                    recipe_id = meal.get("recipe_id")
                    if not recipe_id:
                        continue  # Skip meals without linked recipes

                    meal_type = meal.get("meal_type", "lunch").lower()
                    # Map meal_type to Tandoor meal type
                    if "snack" in meal_type:
                        type_id = type_map.get("snack", 1)
                    else:
                        type_id = type_map.get(meal_type, 1)

                    await self.tandoor.create_meal_plan_entry(
                        recipe_id=recipe_id,
                        meal_type_id=type_id,
                        plan_date=plan_date,
                        servings=meal.get("servings", 1.0),
                        title=meal.get("name", ""),
                    )
                    synced_count += 1

            return {"status": "synced", "entries_created": synced_count}

        except Exception as e:
            logger.error(f"Failed to sync meal plan to Tandoor: {e}")
            return {"status": "failed", "error": str(e)}

    async def generate_shopping_list(self, meal_plan: dict) -> list:
        """
        Generate a consolidated shopping list from the meal plan.

        Attempts to use Tandoor's shopping list features where possible,
        falls back to aggregation from recipe data.
        """
        shopping_items = {}

        for day_data in meal_plan.get("days", []):
            for meal in day_data.get("meals", []):
                recipe_id = meal.get("recipe_id")
                if recipe_id:
                    try:
                        # Use Tandoor to get recipe ingredients
                        recipe = await self.tandoor.get_recipe(recipe_id)
                        steps = recipe.get("steps", [])
                        servings = meal.get("servings", 1.0)
                        recipe_servings = recipe.get("servings", 1)
                        multiplier = servings / recipe_servings

                        for step in steps:
                            for ing in step.get("ingredients", []):
                                food = ing.get("food", {})
                                food_name = food.get("name", "Unknown")
                                amount = (ing.get("amount", 0) or 0) * multiplier
                                unit = ing.get("unit", {})
                                unit_name = unit.get("name", "") if unit else ""

                                key = food_name.lower()
                                if key in shopping_items:
                                    shopping_items[key]["quantity"] += amount
                                else:
                                    shopping_items[key] = {
                                        "name": food_name,
                                        "quantity": amount,
                                        "unit": unit_name,
                                        "category": self._categorize_food(food_name),
                                    }
                    except Exception as e:
                        logger.warning(f"Failed to get recipe {recipe_id} ingredients: {e}")

        return [
            {
                "name": item["name"],
                "quantity": f"{item['quantity']:.1f} {item['unit']}".strip(),
                "category": item["category"],
                "checked": False,
            }
            for item in sorted(shopping_items.values(), key=lambda x: x["category"])
        ]

    @staticmethod
    def _categorize_food(name: str) -> str:
        """Simple heuristic to categorize food items for shopping list organization."""
        name_lower = name.lower()
        categories = {
            "Protein": ["chicken", "beef", "pork", "fish", "salmon", "tuna", "shrimp",
                        "turkey", "tofu", "tempeh", "egg"],
            "Dairy": ["milk", "cheese", "yogurt", "cream", "butter"],
            "Produce": ["lettuce", "spinach", "broccoli", "carrot", "tomato", "onion",
                       "pepper", "banana", "apple", "berry", "avocado", "potato",
                       "garlic", "lemon", "lime", "cucumber", "celery"],
            "Grains": ["rice", "pasta", "bread", "oat", "quinoa", "cereal", "flour",
                      "tortilla", "noodle"],
            "Pantry": ["oil", "sauce", "salt", "pepper", "spice", "sugar", "honey",
                      "vinegar", "stock", "broth", "can", "bean"],
            "Frozen": ["frozen"],
        }
        for category, keywords in categories.items():
            if any(kw in name_lower for kw in keywords):
                return category
        return "Other"
